# Generated by Django 3.2.7 on 2021-09-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='image',
            field=models.ImageField(default=None, upload_to='', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
