# Generated by Django 3.2.7 on 2021-09-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_newpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
